default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: kintai_development
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  <<: *default
  host: 127.0.0.1
  database: kintai_test
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>

production:
  <<: *default
  database: kintai
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
