default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: kintai_development
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  <<: *default
  # GithubActionsでテスト実行するために、環境変数でURLを明示する
  # ※.github/workflows/ruby.ymlの環境変数「database_url」に対応
  host: <%= ENV['DATABASE_URL'] %>
  database: kintai_test
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>

production:
  <<: *default
  database: kintai
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
