default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: kintai_development

test:
  <<: *default
  database: kintai_test

production:
  <<: *default
  database: kintai
