name: RSpec

# master,developmentブランチへのPush時に実行
on:
  # 以下の条件をトリガーに動作させる
  # 1. 所定のブランチに対してPushされた時
  push:
    branches: [master, development]
  # 2. masterブランチにプルリクされた時
  pull_request:
    branches: [master]

jobs:
  run_spec:
    name: Run spec

    # ジョブを実行する仮想マシンを選択
    # 例：
    # macos-latest
    # windows-latest
    runs-on: ubuntu-latest

    # Gitのコミットメッセージの先頭に「ga skip」がある場合は、GithubActionsをスキップさせる
    # ※GithubActionsの無料枠を節約するため
    if: "!contains(github.event.head_commit.message, 'ga skip')"
    services:
      # PostgreSQLの設定
      posgres:
        image: postgres:13
        # database.ymlに設定されている、テスト用ユーザの接続情報を指定する
        env:
          POSTGRES_USER: kintai_test_user
          POSTGRES_PASSWORD: Kintai@test
          POSTGRES_DB: kintai_test
        # オプションはGithubActionsの公式ドキュメントより引用
        # https://docs.github.com/ja/actions/using-containerized-services/creating-postgresql-service-containers
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # 標準的なチェックアウトアクションを実行(https://docs.github.com/ja/actions/configuring-and-managing-workflows/configuring-a-workflow#using-the-checkout-action)
      # ※キャッシュを使用する
      - uses: actions/checkout@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # 使用するRubyバージョンを指定する
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      # bundle install実行
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # マイグレーション実行
      - name: Setup migrate
        run: |
          rails db:create RAILS_ENV=test
          rails db:migrate RAILS_ENV=test

      # テスト実行
      - name: Test with Rspec
        # gemをインストールし、テストを実行する
        run: |
          gem install bundler
          bundle exec rspec
