name: RSpec

# master,developmentブランチへのPush時に実行
on:
  # 以下の条件をトリガーに動作させる
  # 1. 所定のブランチに対してPushされた時
  push:
    branches: [master, development]
  # 2. masterブランチにプルリクされた時
  pull_request:
    branches: [master]

jobs:
  run_spec:
    name: Run spec

    # ジョブを実行する仮想マシンを選択
    # 例：
    # macos-latest
    # windows-latest
    runs-on: ubuntu-latest

    # Gitのコミットメッセージの先頭に「ga skip」がある場合は、GithubActionsをスキップさせる
    # ※GithubActionsの無料枠を節約するため
    if: "!contains(github.event.head_commit.message, 'ga skip')"
    services:
      # PostgreSQLの設定
      posgres:
        image: postgres:13
        # database.ymlに設定されている、テスト用ユーザの接続情報を指定する
        env:
          RAILS_DATABASE_HOST: postgres
          POSTGRES_DB: kintai_test
          POSTGRES_USER: kintai_test_user
          POSTGRES_PASSWORD: Kintai@test
        # オプションはGithubActionsの公式ドキュメントより引用
        # https://docs.github.com/ja/actions/using-containerized-services/creating-postgresql-service-containers
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # 標準的なチェックアウトアクションを実行(https://docs.github.com/ja/actions/configuring-and-managing-workflows/configuring-a-workflow#using-the-checkout-action)
      - uses: actions/checkout@v2

      # 使用するRubyバージョンを指定する
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      # gemをキャッシュする
      # [path]
      # キャッシュとして保存＆復元するディレクトリのパス。
      #  絶対パスか、プロジェクトのルートディレクトリからの相対パスを指定する。
      #
      # [key]
      # キャッシュを保存＆復元するためのキー。
      # 最大 512 文字で、それ以上の長さの文字列を渡すとエラーになるとのこと
      #
      # [restore-keys]
      # キャッシュ復元時に key に完全に一致するキャッシュが存在しなかったときに使われるキーのリスト(任意、必須ではない)
      #
      # なお、度作成したキャッシュの上書きはできないため、キャッシュキーの先頭にバージョン名など
      # を入れておくと、バージョン番号を変更するだけでキャッシュをまとめて無効化できるため推奨。
      # 例：「actions/cache@v1」→「actions/cache@v2」に変更する
      #     ※OSと連動させたいなら`${{ runner.os }}`と記せば良い。
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ env.cache-version }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          # keyで定義したキーを前方一致で検索して復元
          restore-keys: ${{ env.cache-version }}-bundle-

      # Bunlerインストール
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --quiet --jobs 4 --retry 3

      # テスト実行
      - name: Test with Rspec
        # gemをインストールし、テストを実行する
        run: |
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test
          bundle exec rspec
